package com.ikaihuo.monkey.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public static final String table = "user";

	protected BaseUser() {
		set(TABLE_KEY, BaseUser.table);
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}
	
	public void setAddr(java.lang.String addr) {
		set("addr", addr);
	}

	public java.lang.String getAddr () {
		return get("addr");
	}
}
