package com.ikaihuo.monkey.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProfile<M extends BaseProfile<M>> extends Model<M> implements IBean {

	public static final String table = "profile";

	protected BaseProfile() {
		set(TABLE_KEY, BaseProfile.table);
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUid(java.math.BigInteger uid) {
		set("uid", uid);
	}

	public java.math.BigInteger getUid() {
		return get("uid");
	}

	public void setInfo(java.lang.String info) {
		set("info", info);
	}

	public java.lang.String getInfo() {
		return get("info");
	}

}
