package com.ikaihuo.monkey.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDjh<M extends BaseDjh<M>> extends Model<M> implements IBean {

	public static final String table = "djh";

	protected BaseDjh() {
		set(TABLE_KEY, BaseDjh.table);
	}

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
