package com.ikaihuo.gp.subsystem.api.model;

import com.ikaihuo.gp.subsystem.api.base.model.BaseFireProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireProvince extends BaseFireProvince<FireProvince> {
	
}
