package com.ikaihuo.gp.subsystem.api.model;

import com.ikaihuo.gp.subsystem.api.base.model.BaseFireCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireCity extends BaseFireCity<FireCity> {
	
}
