package com.ikaihuo.gp.subsystem.api.model;

import com.ikaihuo.gp.subsystem.api.base.model.BaseFireDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FireDistrict extends BaseFireDistrict<FireDistrict> {
	
}
