package com.ikaihuo.gp.subsystem.api.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFireDistrict<M extends BaseFireDistrict<M>> extends Model<M> implements IBean {

	public static final String table = "fire_district";

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public void setSortSeq(java.lang.Integer sortSeq) {
		set("sort_seq", sortSeq);
	}

	public java.lang.Integer getSortSeq() {
		return get("sort_seq");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIconImage(java.lang.String iconImage) {
		set("icon_image", iconImage);
	}

	public java.lang.String getIconImage() {
		return get("icon_image");
	}

	public void setInUse(java.lang.Boolean inUse) {
		set("in_use", inUse);
	}

	public java.lang.Boolean getInUse() {
		return get("in_use");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String POST_CODE = "post_code";

	public void setPostCode(java.lang.String postCode) {
		set("post_code", postCode);
	}

	public java.lang.String getPostCode() {
		return get("post_code");
	}

	public static final String CITY_ID = "city_id";

	public void setCityId(java.lang.Long cityId) {
		set("city_id", cityId);
	}

	public java.lang.Long getCityId() {
		return get("city_id");
	}

}
