package com.ikaihuo.gp.subsystem.api.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFireCity<M extends BaseFireCity<M>> extends Model<M> implements IBean {

	public static final String table = "fire_city";

	protected BaseFireCity() {
		set(TABLE_KEY, BaseFireCity.table);
	}

	public static final String ID = "id";

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public static final String CREATE_DATE = "create_date";

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public static final String MODIFY_DATE = "modify_date";

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

	public static final String SORT_SEQ = "sort_seq";

	public void setSortSeq(java.lang.Integer sortSeq) {
		set("sort_seq", sortSeq);
	}

	public java.lang.Integer getSortSeq() {
		return get("sort_seq");
	}

	public static final String AREA_CODE = "area_code";

	public void setAreaCode(java.lang.String areaCode) {
		set("area_code", areaCode);
	}

	public java.lang.String getAreaCode() {
		return get("area_code");
	}

	public static final String DESCRIPTION = "description";

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public static final String ICON_IMAGE = "icon_image";

	public void setIconImage(java.lang.String iconImage) {
		set("icon_image", iconImage);
	}

	public java.lang.String getIconImage() {
		return get("icon_image");
	}

	public static final String IN_USE = "in_use";

	public void setInUse(java.lang.Boolean inUse) {
		set("in_use", inUse);
	}

	public java.lang.Boolean getInUse() {
		return get("in_use");
	}

	public static final String NAME = "name";

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public static final String PROVINCE_ID = "province_id";

	public void setProvinceId(java.lang.Long provinceId) {
		set("province_id", provinceId);
	}

	public java.lang.Long getProvinceId() {
		return get("province_id");
	}

}
