package com.ikaihuo.monkey.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import java.util.*;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal-Ext2.
 */
public class GalayTableMappingKit {

	private final Map<Class<? extends Model<?>>, String> modelToTableMap = new HashMap<Class<? extends Model<?>>, String>();
	private final Map<String, Class<? extends Model<?>>> tableToModelMap = new HashMap<String, Class<? extends Model<?>>>();
	private static GalayTableMappingKit me = new GalayTableMappingKit();

	public static GalayTableMappingKit me() {
		return me;
	}

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("djh", "id", Djh.class);
		arp.addMapping("profile", "id", Profile.class);
		arp.addMapping("user", "id", User.class);
	}

	public void putTable(Class<? extends Model<?>> modelClass, String tableName) {
		this.modelToTableMap.put(modelClass, tableName);
	}
	public void putTable(String tableName, Class<? extends Model<?>> modelClass) {
		this.tableToModelMap.put(tableName, modelClass);
	}

	public String getTableName(Class<? extends Model<?>> modelClass) {
		if (!this.modelToTableMap.containsKey(modelClass)) {
			return "";
		}
		return this.modelToTableMap.get(modelClass);
	}

	public Class<? extends Model<?>> getModelClass(String tableName) {
		if (!this.tableToModelMap.containsKey(tableName)) {
			return null;
		}
		return this.tableToModelMap.get(tableName);
	}

	private GalayTableMappingKit() {
		this.modelToTableMap.put(Djh.class, "djh");
		this.tableToModelMap.put("djh", Djh.class);
		this.modelToTableMap.put(Profile.class, "profile");
		this.tableToModelMap.put("profile", Profile.class);
		this.modelToTableMap.put(User.class, "user");
		this.tableToModelMap.put("user", User.class);
	}
}

