package com.ikaihuo.monkey.model;

import com.ikaihuo.monkey.base.model.BaseProfile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Profile extends BaseProfile<Profile> {
	
}
